### ISSUE TITLE
Possible formatting directive in Println call

### ISSUE THREAD

**Issue by lerrua** [nuveo/logSys#10]
Guys,

I'm seeing this error when I write `log.Println()`: possible formatting directive in Println.
The solution is changing this method name, ref: https://github.com/derekparker/delve/issues/783

**Comment by rogeriozambon** [comment]
@lerrua, I'd several tests to try reproduce it, but this issue was solved with https://github.com/nuveo/log/commit/4186eaf9ade20f4f8397ef59d970ab97096ce614 commit, right?
